- < ol > makes a ordered list
- < li > makes a list item
- < ul > is an unordered list
- < li > list item
- < Dl >is definition list
- < Dt > definition term
- You can use div to set a section and there for added CSS to it
- Border width is the property used to control the border
- Border style is used to set the outline of a border for example dashed.
- Border Color determines the color
- Padding is the spacing
- Text align center will center your words in a box
- Visibility hidden will hide the border.
- Java

- For loop = For (var I =0; I < 10; i++){document.write(i); 
